Seagate/cortx-rgw-integration

src/setup/rgw.py

**Issue :**  Previosuly we were not assigning any capabilities to admin user creation process which was happening during rgw deployment process.
We have seen issue when CSM tries to create iam user using this admin access key it fails with "**Access Denied**" issue.
**Fix :** while creating admin user in rgw, we need to add capabilities as below,
`radosgw-admin user create --uid=admin_user --display-name="admin_user" --caps="users=*;metadata=*;usage=*;zone=*" --no-mon-config` …

CORTX-28840:RGW: Add admin capabalities to rgw admin user

---

src/setup/rgw.py

- RGW:Log Rotation: code improvement
-  Currently file '/etc/logrotate.d/ceph' is getting renamed to '/etc/logrotate.d/radosgw'
Instead of renaming old file, creating a new file and removing old file.
so, that in case, old file is not present, it should not impact the rest of the code.

CORTX-28906: RGW Log rotation code Improvement

---

src/setup/rgw.py

- rgw_setup config phase failed since rgw_user_create method does not return anything if lock is acquired
-  Move retry logic into rgw_lock=True block

CORTX-28871: Modify admin user retry logic into rgw_lock block

---

setup.py
src/rgw/const.py
src/rgw/setup/rgw.py
src/rgw/setup/templates/logrotate.service.tmpl
src/rgw/setup/templates/rgw.logrotate.tmpl

…in cortx-server pod
- RGW log files are not getting rotated in cortx-server pod
-  Enable crond service and configure logrotate for radosgw on hourly basis

CORTX-29433: RGW: Start crond service on hourly basis to enable logrotate for RGW files

---

src/rgw/support/rgw_support_bundle

- According to current implementation, rgw support bundle will raise error, if config file is missing.
- support bundle should skip the config file if missing, and bundle up other log files present.

CORTX-29227: RGW: support bundle should be generated even if config file is missing

---

src/rgw/const.py
src/rgw/setup/rgw.py
src/rgw/setup/rgw_setup

Refine Config Structure for RGW
MOTR clients i.e. using service names as client names, e.g. "motr_client" "rgw_s3"
RGW Mini Provisioner to be verified with "rgw_setup --service=rgw_s3" 
Reference doc : https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/611615649/CORTX+Configuration+Parameters?src=mail&src.mail.action=view&src.mail.notification=com.atlassian.confluence.plugins.confluence-notifications-batch-plugin%3Abatching-notification&src.mail.recipient=8a7f808a7812f7f70178188db13e05bf&src.mail.timestamp=1648099792383 
Checklist for …

CORTX-29705:RGW:updation of rgw service name as rgw -> rgw_s3 in motr client & --services parameters

---

src/rgw/support/rgw_support_bundle

JIRA: https://jts.seagate.com/browse/CORTX-29690
- users won't be able to remember all the options of support bundle, so adding `--all`
option to set all flags to true for collecting all logs
-  added `--all` option to collect  stacktrace, binlogs and coredumps with single option

Add --all option in support bundle to collect all logs including stacktrace, binlogs and coredumps

---

src/rgw/const.py
src/rgw/setup/rgw.py

RGW mini-provisioner will create Addb logs directory as : **/etc/cortx/log/rgw/{machine-id}/addb_files-{motr fid value}/**

CORTX-29729:RGW:create addb stob log directory

---

src/rgw/setup/rgw.py

In case of admin user creation failure, m0trace files are created in /root directory .Hence adding the logic of mini-provisioner where m0trace files will be created in pvc location instead of /root.

CORTX-30969:Use PVC location for storing m0trace files during mini-provisioner execution

---

conf/cortx_rgw.conf

Signed-off-by: saurabh jain <saurabh.jain2@seagate.com>
The current default value of rgw_concurrent_max_requests is set very high compared to default thread pool size.
```
rgw_concurrent_max_requests = 1024
rgw_thread_pool = 10
```
Given the limited resource availability in the VM environment and the size of threadpool in rgw server we should keep rgw_concurrent_max_requests to equal to rgw thread pool size.

change rgw concurrent request parameter

---

conf/cortx_rgw.conf
src/rgw/const.py

1. Enabling addb log generation in motr using rgw config file.
2. Currently addb dependent ticket [CORTX-29019](https://jts.seagate.com/browse/CORTX-29019) is not merged hence for our ticket , we will still introduce rgw config parameter in rgw config file during deployment but the value of that flag will be "false" instead of true.
3. once this addb dependency ticket gets merged, we will change the default value from "false" to "true" in cortx-rgw-integration repo by creating separate PR.
Checklist for …

CORTX-29728:RGW:add 'motr enable addb = false' parameter in rgw config

---

src/rgw/const.py
src/rgw/setup/rgw_setup

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>
- add default argument for --changeset in case it is not provided in mini provisioner cmd.
tested PR with rolling upgrade flow and upgrade mini provisioner was passed:
2022-05-30 09:05:30 cortx_setup [43]: INFO [cluster_upgrade] Starting cluster upgrade on 65b197d7f8354f58ab0668578bcc8f66:cortx-server-headless-svc-ssc-vm-rhev4-2766
2022-05-30 09:05:30 cortx_setup [43]: INFO [_provision_components] /opt/seagate/cortx/utils/bin/utils_setup upgrade --config …

CORTX-30211: added default argument for --changeset

---

jenkins/build.sh

On centos vm, if we enable addb plugin build, rpm build shows failure with below message,
To fix this, we need to set '%_binaries_in_noarch_packages_terminate_build 0' macro value.

CORTX-32045 : cortx-rgw-integration: fixing rpm generation issue with addb plugin binary

---

src/rgw/const.py
src/rgw/support/rgw_support_bundle

JIRA : https://jts.seagate.com/browse/CORTX-29735
- core dumps are not captured in rgw support bundle
-  CRASHDUMP path is updated

CORTX-29735: Collect rgw core files as a part of rgw support bundle script

---

src/rgw/support/rgw_support_bundle

JIRA: https://jts.seagate.com/browse/CORTX-31981
- m0trace trace is disabled by default
-  set default behavior to always include m0trace file in support bundle and created ticket https://jts.seagate.com/browse/CORTX-32151 to generate stacktrace and add to supportbundle

CORTX-31981: Include motr trace files in rgw support bundle by default

---

src/rgw/support/rgw_support_bundle

JIRA: https://jts.seagate.com/browse/CORTX-31981
- m0trace files are in binary format
-  converted m0trace files to yaml format using command `m0trace -i <input file> -Y -o <output file>`

CORTX-31981: convert motor trace files from binary to yaml before bundling

---

src/rgw/const.py
src/rgw/setup/rgw.py

**Problem:**
-    In rgw mini-provisioner phase, we are fetching data pod endpoint (hostname) value using one hardcoded string "node>machine-id>type" as "data_node"
-    This hardcoded needs to be removed and data pod identification can be done with another keys.
**Solution**
-   Use Conf.search() api to identify data pods available in cluster.conf file.
-   From above list, get the hostnames of data pods. 

CORTX-32367:Remove hardcoded data node type value from const.py

---

src/rgw/setup/radosgw_start
src/rgw/support/rgw_support_bundle

Signed-off-by: rohit-k-dwivedi <rohit.k.dwivedi@seagate.com>
JIRA: [CORTX-32151](https://jts.seagate.com/browse/CORTX-32151)
also resolves the BUG: [CORTX-32323](https://jts.seagate.com/browse/CORTX-32323)
- No stack trace available for radosgw process
-  [CORTX-32151](https://jts.seagate.com/browse/CORTX-32151) : triggered `gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" /usb/bin/radosgw <pid>` which sends output of bt which is written into `radosgw_bt.log` file
- [CORTX-32323](https://jts.seagate.com/browse/CORTX-32323) : along with this change, also addressed the change to add milliseconds in timestamp appending.
as there was no way to add millis in timestamp using gawk and strftime, change logic to 
-  [x] Coding conventions are followed and code is …

CORTX-32323 , CORTX_32151: generate stack trace for radsgw process and add millisec to log timestamp

---

src/rgw/setup/rgw.py

Problem : 
During debugging of https://jts.seagate.com/browse/CORTX-33293, we saw when rgw mini-provisioner tries to create admin user in multi data pod environment,, it crashes in motr and result into radosadmin cli crash.
For this crash we did not see any core files generated for rgw .
solution:
change the working directory to pvc path and then try to create user.

CORTX-33543:rgw-integration:collect radosadmin cli core files

---

src/rgw/const.py
src/rgw/setup/rgw.py

Problem:
Provisioner team is planning to migrate file based Gconf to consule based Gconf.
In order to do this, rgw component needs some changes to support this migration. 
Solution:
There are changes required in way we fetch the endpoints values from Gconf e.g. consul endpoint, service endpoint ports.
Approach we took is,  
a) for any key we want to fetch, first  we need to fetch num_client/num_endpoints key from Gconf.
b) based on this number, we need to iterate over each key and get desired value of key.
Checklist for …

CORTX-32738: rgw: rgw support for provisioner Gconf migration to consul

---

src/rgw/const.py
src/rgw/support/rgw_support_bundle

Signed-off-by: rohit-k-dwivedi <rohit.k.dwivedi@seagate.com>
- NO time filter in rgw support bundle
- implemented time base log filter using cortx-utils limit_time method

CORTX-33037: apply support bundle time filter

---

jenkins/build.sh

In build.sh file, we hardcoded python3.6 binary path.
Hence removed this hardcoding and used python3 which is symbolic link of python3.6 
Tomorrow if we plan to upgrade python version then our code will still work.

CORTX-30014:Remove hardcoding of python3.6 from build.sh file

---

conf/cortx_rgw.conf

As part of [F-58D](https://jts.seagate.com/browse/CORTX-29950), all CORTX components are updating their logging setups to support both log files and stderr output. This is important for Kubernetes environments, where logs should be accessible via `kubectl logs`. Currently, RGW server only sends its logs to a file.
RGW supports logging to both file and stderr simultaneously. This PR adds a few logging-related options to the RGW config template to log to both locations. The existing log file setup is not changed, this PR just tees log messages to stderr as well. Full details on RGW logging config are available [here](https://docs.ceph.com/en/quincy/rados/troubleshooting/log-and-debug/#logging-settings).
I tested out deployment with these options, and found the same log messages in both …

CORTX-30240: Log to both stderr and file for k8s environments

---

conf/cortx_rgw.conf
src/rgw/const.py

Added GC parameters to rgw config.
rgw enable gc threads = true
rgw gc obj min wait = 7200        # 2hours
rgw gc processor period = 3600    # 1hour
rgw gc max concurrent io = 1
rgw gc max trim chunk = 256
rgw gc max objs = 64
rgw gc processor max time = 3600  # 1hour

rgw-integration:[CORTX-32705]:Add GC parameters to mini-provisioner

---

conf/cortx_rgw.conf

Changed GC parameter value 
rgw gc obj min wait : 
Old value : 7200 
New value : 900

CORTX-33999:changed rgw gc obj min wait time to 15 minutes from 2 hours

---

src/rgw/setup/rgw.py
src/rgw/setup/rgw_service.py

Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>
The addb client logs in rgw container is generating in wrong directory (rgw_debug). This "rgw_debug" directories meant for rgw crash files only. Our expectation, addb client logs should be resides in "addb_files-0x7200000000000001:0x13" directory.
-  For Bug, required to create an environment variable for addb directories in "rgw_services.py"

CORTX-32172: Fixes ADDB client logs to bundled it in rgw support bundle

---

src/rgw/const.py
src/rgw/setup/rgw.py

Updated user creation logic as below
1) Move rgw admin creation from config phase to init phase .
- changes suggested by motr team because after hare init phase, motr endpoint will be available. hence rgw should try user creation after this step.
2) Expose admin user creation timeout & retry count parameter as part of GConf and user can set this through solution.yaml.
```
ADMIN_USER_CREATION_TIMEOUT_KEY = f'cortx>{COMPONENT_NAME}>admin_creation_timeout'
ADMIN_USER_CREATION_MAX_RETRY_KEY =  f'cortx>{COMPONENT_NAME}>admin_creation_max_retry'
ADMIN_USER_CREATION_DEFAULT_TIMEOUT = 600
ADMIN_USER_CREATION_MAX_DEFAULT_RETRY = 1
``` …

CORTX-34035: move rgw admin creation logic from config phase to init phase

---

src/rgw/const.py
src/rgw/support/rgw_support_bundle

Signed-off-by: rohit-k-dwivedi <rohit.k.dwivedi@seagate.com>
JIRA: [CORTX-33037](https://jts.seagate.com/browse/CORTX-33037)
- No limit_size filter available
-  Created patch to apply limit_size filter. 
limits number of cores when limit_size is passed and truncates text logs if the size still exceeds

CORTX-33037: apply support bundle filter limit_size

---

conf/cortx_rgw.conf

Observed performance impact if we enable rgw logging on console. 
- Solution
Disable logging messages for rgw service to console.
[client.rgw-1]
log to file = true
log to stderr = false
err to stderr = false

CORTX-33944:Disabling RGW service console logging to address performance issue

---

src/rgw/support/rgw_support_bundle

- Apply limit_time on '.gz' files. 

[CORTX-34050]: Apply limit time filter.

---

src/rgw/const.py
src/rgw/setup/radosgw_start
src/rgw/setup/rgw.py
src/rgw/setup/rgw_service.py

- While starting rgw service, we redirect all the logs to one file which captures all the motr, gc logs to this file.
With latest changes, these logs are already captured hence we don't need to dump into the log file. hence removing this file itself.
- Update m0trace, m0addb log rotation scripts present in /etc/cron.hourly with proper PVC path where motr client logs are stored in rgw container.

CORTX-33043: Update motr log rotate scripts with proper PVC log path and removing rgw startup log file

---

conf/cortx_rgw.conf
src/rgw/const.py
src/rgw/setup/rgw.py

Signed-off-by: Priyanka Salunke <priyanka.s.salunke@seagate.com>
- Updated default value and exposed the log level value : `default log level - 10`
- Exposed the config parameters to solution.yaml file : `cortx>rgw>log_level`
- Example:
```
s3:
....
extra_configuration: |
log_level: 30
```

[CORTX-34109] Updated rgw log level default value and exposed it to solution.yaml

---

src/rgw/const.py
src/rgw/setup/rgw.py

If user provide any of these parameters in solution.yaml file then we will skip resource limit based formula calculation and we will pick up user specified value.
if solution.yaml file does not has these keys in extra_configuration section then we will generate values using resource limit based formula.
example soultion.yaml ,
"
   s3:
      default_iam_users:
        auth_admin: sgiamadmin
        auth_user: user_name
      max_start_timeout: 240
      instances_per_node: '1'
      extra_configuration: |
thread_pool_size: 30
max_concurrent_requests: 33
        enable_gc_threads: 'false'
"
-  [ ] Coding …

CORTX-34161: exposing thread_pool_size & max_concurrent_requests parameters in solution.yaml for rgw

---

conf/cortx_rgw.conf

Enabled back RGW stdout/stderr logging
Signed-off-by: Chetan S. Deshmukh <chetan.deshmukh@seagate.com>
- RGW stdout/stderr logging was disabled owing to performance regression reported in CORTX-33944
- After [this change](https://github.com/Seagate/cortx-rgw-integration/pull/124/files#diff-41d93f02c5a69a10187e14688fce682f63a6b77a5e80f9aae86c659fcf35e742R13) was merged, perf issue was resolved, removing code which was reading libMotr log o/p line by line, and prepending timestamp & then pushing it to stdout/stderr

CORTX-30240: Enabling back RGW stdout/stderr logging after confirming IO tests performance results
