Seagate/cortx-rgw-integration

- .github/workflows/dco-check.yml
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
DCO check workflow for RGW Integration
> DCO check workflow for RGW Integration

- CODEOWNERS
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
> Added the codeowners

- .github/pull_request_template.md
- LICENSE
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
-----
[View rendered .github/pull_request_template.md](https://github.com/venkuppu-chn/cortx-rgw-integration/blob/main/.github/pull_request_template.md)
> Added the PR checklist and License

- jenkins/build.sh
- src/setup/__init__.py
- src/setup/error.py
- src/setup/rgw.py
- src/setup/rgw_setup.py
- src/setup/templates/rgw.config.tmpl
Signed-off-by: Ujjwal Lanjewar <ujjwal.lanjewar@seagate.com>
> rgw_setup skeleton (Mini-provisioner + directory structure)

- jenkins/build.sh
- setup.py
- src/support/__init__.py
- src/support/rgw_support_bundle
- src/support/support.yaml
- Support Bundle for component RGW
- Implemented support bundle script for component RGW
> EOS-28431: Support Bundle for component RGW

- jenkins/build.sh
- requirements.txt
- setup.py
> EOS-27796: Added RPM level dependencies.

- src/const.py
- src/setup/rgw.py
> Updated required RPM list. [post install validation.]

- conf/cortx_rgw.conf
- src/const.py
- src/setup/rgw.py
> Fix config keys in cortx_rgw.conf

- .gitignore
List of directories which will be ignore from git check,
1. build/
2. cortx_rgw_integration.egg-info/
3. dist/
> created git ignore list for pre-staged directories

- src/setup/rgw.py
> deployment issue for m0 endpoint reusability

- src/const.py
- src/support/rgw_support_bundle
- Improvement for support bundle for RGW - config path update
-  Removed Hard coded config path and reading the path from conf file.
> EOS-27806: Improvement for support bundle for RGW - config path update

- src/const.py
- src/setup/rgw.py
> CORTX-28819-decrypt-secret: Decrypt rgw 'auth_secret'

- src/const.py
- src/setup/rgw.py
- src/setup/rgw_service
> EOS-28594: Enable https endpoints for rgw.

- setup.py
- src/const.py
- src/setup/rgw.py
- src/setup/templates/rgw.logrotate.tmpl
- Configure logrotate for component rgw.
-  Added code to configure logrotate at mini provisioner's prepare stage
> EOS-27805: RGW Log Rotation

- src/const.py
- change logrotate filename from <component_name> to 'radosgw' service
> Fix for rgw log rotation

- src/const.py
- src/setup/rgw.py
…gw backend store value
- Bug id: CORTX-28876:Config phase of RGW mini-provisioning fails to validate rgw backend store value
> CORTX-28876:Config phase of RGW mini-provisioning fails to validate 'rgw backend store' value.

- src/setup/rgw.py
- src/setup/rgw_start.py
- Create admin user in config phase by reading hax endpoint from data pod
> CORTX-28818: Create admin user in config phase

- src/setup/rgw.py
- radosgw-admin.log needs to be corrected
Updated log filepath
> EOS-28962: RGW Log: update filepath

- src/setup/rgw.py
- To Validate hostname of data pod
> CORTX-28890: Validate hostname of data pod

- src/setup/rgw.py
> CORTX-29092:Fix for logrotation config file.

- src/setup/rgw.py
- Validate sysconfig values
-  Values in sysconfig should not be null
> CORTX-28824: Validate sysconfig values (empty string check)

- src/setup/rgw.py
> CORTX-28824: Revert Validation of sysconfig values

- setup.py
- cortx_support_bundle not generating rgw support bundle
-  Added rgw support.yaml
> Fix for rgw_support_bundle integration with cortx_support_bundle

- src/rgw/setup/rgw.py
- src/rgw/setup/rgw_service.py
- src/rgw/support/rgw_support_bundle
- Include libMotr logs in RGW support bundle
- Added m0_trace log files in rgw support bundle
> CORTX-29133: Include libMotr logs in RGW support bundle

- src/rgw/const.py
- src/rgw/setup/rgw.py
- src/rgw/setup/rgw_setup
- src/rgw/support/rgw_support_bundle
- Use generic names to avoid use of `rgw` 
> CORTX-28697: use generic method variable names

- conf/cortx_rgw.conf
- src/rgw/const.py
- src/rgw/setup/rgw.py
Updating rgw config files with additional keys which are for RGW & motr parameters.
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/915276544/CORTX+Config+Keys+for+RGW 
> CORTX-28919:RGW: Add rgw & motr parameters which are not exposed to Gconf

- conf/cortx_rgw.conf
> CORTX-29219-part-2:RGW: adding hardcoded parameter 'rgw cache enabled = false'

- src/rgw/const.py
- src/rgw/setup/rgw.py
> CORTX-28875: RGW: Update port value for rgw.

- src/rgw/const.py
- src/rgw/setup/rgw.py
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/915276544/CORTX+Config+Keys+for+RGW 
> CORTX-29219:RGW: Add rgw & motr parameters which are exposed to Gconf

- src/rgw/const.py
- src/rgw/setup/rgw.py
> CORTX-29573:rgw_setup config failed with object has no attribute decode

- src/rgw/const.py
- src/rgw/setup/rgw.py
> CORTX-29489: support for multiple rgw pod.

- src/rgw/setup/rgw.py
> CORTX-29811: Validate hctl command response

- src/rgw/const.py
- src/rgw/setup/rgw.py
> CORTX-29937: RGW config phase is failing

- src/rgw/setup/rgw.py
- src/rgw/setup/rgw_service.py
- Fix codacy issue for cortx-rgw-integration repo
Codacy result for this PR: https://app.codacy.com/gh/Seagate/cortx-rgw-integration/dashboard?branch=fix-codacy-issue
> CORTX-30097: Fix codacy issues.

- conf/cortx_rgw.conf
- src/rgw/const.py
- src/rgw/setup/rgw.py
Added default config parameters in the rgw template file.
> CORTX-29711:RGW:adding default parameters to cortx_rgw.conf template 

- src/rgw/setup/rgw.py
- Add more capabilities to the admin user.
**"user", "users", "buckets", "metadata", "info", "usage", "zone", "roles", "user-policy"**
> CORTX-29196: Add more capabilities to the admin user.

- src/rgw/setup/templates/rgw.logrotate.tmpl
- log rotate fetches all the files ending with .log in the log location
-  specified exact name of log files that are intended to rotate
> CORTX-30018: change logrotate config to fetch specific logs

- src/rgw/setup/templates/rgw.logrotate.tmpl
- log rotation not working 
-  removed and additional ? from regex to pick rgw-1.log
> CORTX-30018: Rgw log rotation issue

- src/rgw/const.py
- src/rgw/setup/rgw.py
- Implement the RGW-Upgrade MP interface.
-  Take a backup of deployed rgw conf file - cortx_rgw.conf to cortx_rgw.conf.<version-id>
- Generate new rgw conf file at same location - ie /etc/cortx/rgw/<machine-id>/cortx_rgw.conf.
- If upgrade fails, revert backup file to original file ie cortx_rgw.conf.<version-id> to cortx_rgw.conf.
> CORTX-29892: Upgrade mini-provisioner interface.

- src/rgw/setup/rgw.py
- default connection check for consul takes almost 2 minutes of timeout, adding 3 retries with exponential backoff logic adds 7 sec + 4x60sec ie almost 8min 7 sec
- introduced check for consul using socket which checks if the server is alive with a timeout of 2 sec and 4 re-tries
creates a fast fail which fails within 15sec .
> CORTX-29889: add consul alive check for FAST FAILURE in rgw miniprovisioning

- src/rgw/setup/rgw.py
- socket accepts int value for port
> CORTX-29889: patch for int port

- src/rgw/support/rgw_support_bundle
- Add addb logs to rgw support bundle
JIRA: https://jts.seagate.com/browse/CORTX-30595
-  added rgw logs to support bundle
> CORTX-30595: add addb logs to rgw support bundle

- conf/cortx_rgw.conf
> Added comment in RGW config file.

- README.md
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Added other Badges
-----
[View rendered README.md](https://github.com/Seagate/cortx-rgw-integration/blob/mukul-badges/README.md)
> CORTX-30686: Added other Badges

- src/rgw/const.py
- src/rgw/setup/rgw.py
- src/rgw/setup/rgw_setup
> CORTX-29893:rgw: handle upgrade in cortx-rgw-integration

- conf/cortx_rgw.conf
> CORTX-31340:set  motr addb enabled = true in rgw config file

- src/rgw/setup/rgw.py
- Avoid redundant logs, improve log relevance.
> CORTX-33288: Avoid redundant logs, improve log relevance.
